# Allow the Cloud Provider to set the port, default to 8080 locally
server.port=${PORT:8080}

# Database Configuration injected via Environment Variables
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Disable open-in-view warning
spring.jpa.open-in-view=false