spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=vijay
spring.datasource.password=*Vijay1990
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true